### ISSUE TITLE
Would this support Wiredep then?

### ISSUE THREAD

**Issue by weilinzung** [sheerun/bower-away#22]
Would this support Wiredep then after the migration?

**Comment by mirelm** [comment]
I am struggling at the moment with it. So I will say no. It does not support Wiredep. Wiredep expects a bower.json which does not exist any more.

**Comment by sheerun** [comment]
The only thing that is missing is auto-generated `.bower.json`. You'd need to write Yarn post-install script that generates these. If you manage to do so (please share!), then Wiredep should work.

**Comment by h0wXD** [comment]
Does this do the job https://github.com/johnnyasantoss/wiredep-away ?

**Comment by azachar** [comment]
@h0wXD No, it doesn't do the job.

**Comment by azachar** [comment]
In order to ditch `wiredep`, I forked the original `wiredep` and added tests for `bower-away` support on LTS NodeJS versions inspired by johnnyasantoss/wiredep-away.

Feel free to install it from my master branch at https://github.com/azachar/wiredep-away instead of your original wiredep.
Perhaps it would be cool to integrate it back into wiredep directly since I did not break backward compatibility.

**Comment by azachar** [comment]
Also, i did a fork of grunt-wiredep to support bower-away approach, now replace your `grunt-wiredep` with `azachar/grunt-wiredep-away`

```bash
 yarn add azachar/grunt-wiredep-away#master
```

Hoping that it helps you to convert your old projects :)
